{% set name = "streamlit" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/streamlit-{{ version }}.tar.gz
  sha256: f13f7463d53fb866a1d07dccfacb60333c56dc9f34b001f310475beee71a08a5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - streamlit = streamlit.cli:main

requirements:
  host:
    - pip
    - python >=3.6
    - pipenv
  run:
    - altair >=3.2.0
    - astor
    - base58
    - blinker
    - boto3
    - botocore >=1.13.44
    - cachetools >=4.0
    - click >=7.0, <8.0
    - gitpython
    - numpy
    - packaging
    - pandas >=0.21.0, <1.3.0
    - pillow >=6.2.0
    - protobuf >=3.6.0, !=3.11
    - pyarrow
    - pydeck >=0.1.dev5
    - pympler >=0.9
    - python >=3.6
    - python-dateutil
    - requests
    - toml
    - tornado >=5.0
    - tzlocal
    - validators
    - watchdog

test:
  imports:
    - streamlit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://streamlit.io
  summary: The fastest way to build data apps in Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
    - randyzwitch
    - kmcgrady
