{% set name = "streamlit" %}
{% set version = "0.73.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/streamlit-{{ version }}.tar.gz
  sha256: 6db734ca36c2c7beb3148c9894b1116837cd9f6d587446c56a3f4cde0453b726

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - pipenv
  run:
    - altair >=3.2.0
    - astor
    - base58
    - blinker
    - boto3
    - botocore >=1.13.44
    - cachetools >=4.0
    - click >=7.0
    - gitpython
    - numpy
    - packaging
    - pandas >=0.21.0
    - pillow >=6.2.0
    - protobuf >=3.6.0
    - pyarrow
    - pydeck >=0.1.dev5
    - python >=3.6
    - python-dateutil
    - requests
    - toml
    - tornado >=5.0
    - tzlocal
    - validators
    - watchdog

test:
  imports:
    - streamlit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://streamlit.io
  summary: The fastest way to build data apps in Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
    - randyzwitch
    - karriebear
