{% set name = "streamlit" %}
{% set version = "1.26.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 25475fb15a3cc9fb184945f3fc936f011998bd8386e0c892febe14c9625bf47a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - streamlit = streamlit.cli:main
  skip: true  # [s390x or py<38]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python <3.9.7,>3.9.7,<4.0
    - altair >=4.0,<6
    - blinker >=1.0.0,<2
    - cachetools >=4.0,<6
    - click >=7.0,<9
    - importlib-metadata >=1.4,<7
    - numpy >=1.19.3,<2
    - packaging >=16.8,<24
    - pandas >=1.3.0,<3
    - pillow >=7.1.0,<10
    - protobuf >=3.20,<5
    - pyarrow >=6.0
    - pympler >=0.9,<2
    - python-dateutil >=2.7.3,<3
    - requests >=2.18,<3
    - rich >=10.14.0,<14
    - tenacity >=8.1.0,<9
    - toml >=0.10.1,<2
    - typing_extensions >=4.1.0,<5
    - tzlocal >=1.1,<5
    - validators >=0.2,<1
    - watchdog >=2.1.5  # [not osx]
    # Snowpark extra dependencies are gitpython, pydeck, and tornado:
    # Pin GitPython version not equal to 3.1.19 to avoid builds crush, see https://github.com/streamlit/streamlit/pull/3599
    - gitpython >=3.0.7,<4,!=3.1.19
    - pydeck >=0.8.0,<1
    - tornado >=6.0.3,<7

test:
  imports:
    - streamlit
  requires:
    - pip
  commands:
    # skip pip check because of "streamlit 1.26.0 has requirement pydeck<1,>=0.8, but you have pydeck 0.8.0b4."
    #- pip check

about:
  home: https://streamlit.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The fastest way to build data apps in Python
  description: |
    Streamlit lets you turn data scripts into sharable web apps in minutes, not weeks.
    It's all Python, open-source, and free!
  doc_url: https://docs.streamlit.io/
  dev_url: https://github.com/streamlit/streamlit


extra:
  recipe-maintainers:
    - raybellwaves
    - randyzwitch
    - kmcgrady
