{% set name = "streamlit" %}
{% set version = "1.24.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: "fd5f0b64798e9706364408fb589b77595314a6315d13b2d750b963c7ae97f362"

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - streamlit = streamlit.cli:main
  skip: true  # [s390x or py<38]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - altair >=4.0,<6
    - blinker >=1.0.0,<2
    - cachetools >=4.0,<6
    - click >=7.0,<9
    - importlib-metadata >=1.4,<7
    - numpy {{ numpy }}
    - packaging >=14.1,<24
    - pandas >=0.25.0,<3
    - pillow >=6.2.0,<10
    - protobuf >=3.20,<5
    - pyarrow >=4.0
    - pympler >=0.9,<2
    - python !=3.9.7
    - python-dateutil >=2,<3
    - requests >=2.4,<3
    - rich >=10.11.0,<14
    - tenacity >=8.0.0,<9
    - toml <2
    - typing_extensions >=4.0.1,<5
    - tzlocal >=1.1,<5
    - validators >=0.2,<1
    - watchdog  # [not osx]
    # Snowpark extra dependencies are gitpython, pydeck, and tornado:
    # Pin GitPython version not equal to 3.1.19 to avoid builds crush, see https://github.com/streamlit/streamlit/pull/3599
    - gitpython >=3,<4,!=3.1.19
    - pydeck >=0.1.dev5,<1
    - tornado >=6.0.3,<7

test:
  imports:
    - streamlit
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://streamlit.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The fastest way to build data apps in Python
  description: |
    Streamlit lets you turn data scripts into sharable web apps in minutes, not weeks.
    It's all Python, open-source, and free!
  doc_url: https://docs.streamlit.io/
  dev_url: https://github.com/streamlit/streamlit


extra:
  recipe-maintainers:
    - raybellwaves
    - randyzwitch
    - kmcgrady
