{% set name = "streamlit" %}
{% set version = "1.37.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 463ef728ba21e74e05122e3704e8af644a7bdbb5822e281b8daf4a0a48761879

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - streamlit = streamlit.web.cli:main
  skip: true  # [s390x or py<38]

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    - altair >=4.0,<6
    - blinker >=1.0.0,<2
    - cachetools >=4.0,<6
    - click >=7.0,<9
    - numpy >=1.20,<3
    - packaging >=20,<25
    - pandas >=1.3.0,<3
    - pillow >=7.1.0,<11
    - protobuf >=3.20,<6
    - pyarrow >=7.0
    - requests >=2.27,<3
    - rich >=10.14.0,<14
    - tenacity >=8.1.0,<9
    - toml >=0.10.1,<2
    - typing_extensions >=4.3.0,<5
    - watchdog >=2.1.5,<5  # [not osx]
    - gitpython >=3.0.7,<4,!=3.1.19
    - pydeck >=0.8.0,<1
    - tornado >=6.0.3,<7

test:
  imports:
    - streamlit
  requires:
    - pip
  commands:
    - pip check
    - streamlit --help

about:
  home: https://streamlit.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The fastest way to build data apps in Python
  description: |
    Streamlit lets you turn data scripts into sharable web apps in minutes, not weeks.
    It's all Python, open-source, and free!
  doc_url: https://docs.streamlit.io/
  dev_url: https://github.com/streamlit/streamlit


extra:
  recipe-maintainers:
    - raybellwaves
    - randyzwitch
    - kmcgrady
