{% set name = "streamlit" %}
{% set version = "1.42.0" %}

package:
  name: {{ name|lower }}-split
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 8c48494ccfad33e7d0bc5873151800b203cb71203bfd42bc7418940710ca4970
    folder: streamlit
  - url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
    sha256: d13d8ed5f0b8b429febe0868619d7b42298e7badba266ee7fa73823039ce7de8
    folder: streamlit_tests

build:
  number: 0
  # toml is not avaaliable on linux-s390x
  skip: True  # [py<39]
  # https://github.com/streamlit/streamlit/blob/1.42.0/lib/setup.py#L143
  # python_requires=">=3.9, !=3.9.7"
  skip: True  # [s390x]
  # Watchdog is not avaliable on win + py313
  skip: True  # [win and py>312]

requirements:
  host:
    - python
  run:
    - python

outputs:
  - name: streamlit
    script: build-output.sh  # [not win]
    script: build-output.bat  # [win]
    build:
      entry_points:
        - streamlit = streamlit.web.cli:main
    requirements:
      host:
        - pip
        - python
        - wheel
        - setuptools
      run:
        - python
        - altair >=4.0,<6
        - blinker >=1.0.0,<2
        - cachetools >=4.0,<6
        - click >=7.0,<9
        - numpy >=1.23,<3
        - packaging >=20,<25
        - pandas >=1.4.0,<3
        - pillow >=7.1.0,<12
        - protobuf >=3.20,<6
        - pyarrow >=7.0
        - requests >=2.27,<3
        - rich >=10.14.0,<14
        - tenacity >=8.1.0,<10
        - toml >=0.10.1,<2
        - typing_extensions >=4.4.0,<5
        - watchdog >=2.1.5,<7  # [not osx]
        - gitpython >=3.0.7,<4,!=3.1.19
        - pydeck >=0.8.0b4,<1
        - tornado >=6.0.3,<7
      run_constrained:
        - snowflake-snowpark-python >=1.17.0  # [py<312]
        - snowflake-connector-python >=3.3.0  # [py<312]
        - python !=3.9.7
    test:
      imports:
        - streamlit
      commands:
        - pip check
        - streamlit --help
      requires:
        - pip

  - name: streamlit-tests
    build:
    requirements:
      host:
        - {{ pin_subpackage('streamlit', exact=True) }}
      run:
        - {{ pin_subpackage('streamlit', exact=True) }}

    # ModuleNotFoundError: No module named python-graphviz
    {% set ignore_tests = "" %}
    {% set ignore_tests = ignore_tests + " --ignore=streamlit_tests/lib/tests/streamlit/elements/graphviz_test.py" %}  # [py>312]

    # assert """Authentication credentials in `.streamlit/secrets.toml` are missing the "redirect_uri" key. Please check your configuration.""" == str(ex.exception)
    {% set ignore_tests = " --ignore=streamlit_tests/lib/tests/streamlit/user_info_test.py" %}

    # AssertionError: (1, 6, 4) != None
    {% set ignore_tests = ignore_tests + " --ignore=streamlit_tests/lib/tests/streamlit/git_util_test.py" %}

    # AssertionError: Expected 'warning' to have been called once. Called 0 times.
    {% set ignore_tests = ignore_tests + " --ignore=streamlit_tests/lib/tests/streamlit/watcher/local_sources_watcher_test.py" %}
    {% set ignore_tests = ignore_tests + " --ignore=streamlit_tests/lib/tests/streamlit/config_test.py" %}

    # AssertionError: 'not/a/real/path' != 'not\\a\\real\\path'
    {% set tests_to_skip = "" %}
    {% set tests_to_skip = "test_only_path_pathlib" %}  # [win]

    # AssertionError: Expected 'help' to be called once. Called 0 times.
    {% set tests_to_skip = tests_to_skip + " or test_st_write" %}  # [win]

    # AssertionError: 3 != 2 : Stack does not have length 2
    {% set tests_to_skip = tests_to_skip + " or test_external_error_stack_starts_with_user_module_3" %}  # [win]

    # AssertionError: '<property object at 0x000001F655315450>' != ''
    {% set tests_to_skip = tests_to_skip + " or test_class_members" %}  # [win]

    # AssertionError: 'C:\\some_path\\to\\app\\static' != '/some_path/to/app/static'
    {% set tests_to_skip = tests_to_skip + " or test_get_app_static_dir" %}  # [win]
    {% set tests_to_skip = tests_to_skip + " or test_get_project_streamlit_file_path" %}  # [win]
    {% set tests_to_skip = tests_to_skip + " or test_streamlit_write_exception" %}  # [win]
    {% set tests_to_skip = tests_to_skip + " or test_get_main_script_directory" %}  # [win]
    {% set tests_to_skip = tests_to_skip + " or test_normalize_path_join" %}  # [win]

    # AssertionError: unexpectedly None
    {% set tests_to_skip = tests_to_skip + " or test_persist_path" %}  # [win]
    {% set tests_to_skip = tests_to_skip + " or test_non_hashable" %}  # [win]

    # AssertionError: expected call not found.
    {% set tests_to_skip = tests_to_skip + " or test_Credentials_save" %}  # [win]

    # AssertionError: assert 'C:\\this\\is\\my\\dir' == '/this/is/my/dir'
    {% set tests_to_skip = tests_to_skip + " or test_correctly_resolves_watched_file_path" %}  # [win]
    {% set tests_to_skip = tests_to_skip + " or test_correctly_resolves_watched_folder_path" %}  # [win]

    # AssertionError: expected call not found.
    {% set tests_to_skip = tests_to_skip + " or test_watch_dir_kwarg_plumbing" %}  # [win]

    # AssertionError: Expected 'help' to be called once. Called 0 times.
    {% set tests_to_skip = tests_to_skip + " or test_obj_instance" %}  # [win]
    {% set tests_to_skip = tests_to_skip + " or test_repr_html" %}  # [win]
    {% set tests_to_skip = tests_to_skip + " or test_repr_html_no_html_tags_in_string" %}  # [win]
    {% set tests_to_skip = tests_to_skip + " or test_repr_html_not_callable" %}  # [win]

    # AttributeError: module 'numpy' has no attribute 'bool8'. Did you mean: 'bool'?
    {% set ignore_tests = ignore_tests + " --ignore=streamlit_tests/lib/tests/streamlit/delta_generator_test.py" %}  # [py>312]
    {% set ignore_tests = ignore_tests + " --ignore=streamlit_tests/lib/tests/streamlit/elements/plotly_chart_test.py" %}  # [py>312]
    {% set ignore_tests = ignore_tests + " --ignore=streamlit_tests/lib/tests/streamlit/runtime/caching/cache_data_api_test.py" %}  # [py>312]
    {% set ignore_tests = ignore_tests + " --ignore=streamlit_tests/lib/tests/streamlit/runtime/caching/cache_resource_api_test.py" %}  # [py>312]
    {% set ignore_tests = ignore_tests + " --ignore=streamlit_tests/lib/tests/streamlit/runtime/fragment_test.py" %}  # [py>312]
    {% set ignore_tests = ignore_tests + " --ignore=streamlit_tests/lib/tests/streamlit/runtime/state/widgets_test.py" %}  # [py>312]
    {% set ignore_tests = ignore_tests + " --ignore=streamlit_tests/lib/tests/streamlit/streamlit_test.py" %}  # [py>312]

    # AssertionError: 404 != 200
    {% set ignore_tests = ignore_tests + " --ignore=streamlit_tests/lib/tests/streamlit/streamlit_test.py" %}
    {% set ignore_tests = ignore_tests + " --ignore=streamlit_tests/lib/tests/streamlit/web/server/server_test.py" %}

    # sqlite3.OperationalError: unable to open database file
    {% set tests_to_skip = tests_to_skip + " or test_verify_sqlite3_integration" %}  # [win]

    # PermissionError: [Errno 13] Permission denied: 'C:\\cygwin64\\tmp\\tmp9jhk3u1s.vtt'
    {% set tests_to_skip = tests_to_skip + " or test_st_video_subtitles_path" %}  # [win]

    # UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f6a8' in position 83: character maps to <undefined>
    {% set tests_to_skip = tests_to_skip + " or test_alert" %}  # [win]

    # NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\cygwin64\\tmp\\tmpb98enk00\\tmp6o52qgcdstylesheet.css'
    {% set tests_to_skip = tests_to_skip + " or test_mimetype_is_overridden_by_server" %}  # [win]
    {% set tests_to_skip = tests_to_skip + " or test_nonexistent_urls_return_default_page" %}  # [win]
    {% set tests_to_skip = tests_to_skip + " or test_parse_url_path_200" %}  # [win]
    {% set tests_to_skip = tests_to_skip + " or test_reserved_paths_serve_404" %}  # [win]

    # No such component directory: 'C:\a\test\component\directory'
    {% set tests_to_skip = tests_to_skip + " or test_register_component_with_path" %}  # [win]
    {% set tests_to_skip = tests_to_skip + " or test_register_duplicate_path" %}  # [win]

    # IndexError: pop from empty list
    {% set ignore_tests = ignore_tests + " --ignore=streamlit_tests/lib/tests/streamlit/runtime/runtime_test.py" %}  # [win]

    test:
      source_files:
        - streamlit_tests/lib/tests
        - streamlit_tests/lib/setup.py
      imports:
        - streamlit
      commands:
        - pip check
        - streamlit --help
        - pytest -v {{ ignore_tests }} streamlit_tests/lib/tests  # [not win]
        - pytest -v {{ ignore_tests }} -k "not ({{ tests_to_skip }})" streamlit_tests/lib/tests  # [win]
      requires:
        - pip
        - pytest
        - parameterized 
        # upstream authlib >=1.3.2, but only 1.3.1 is avaliable in main
        - authlib >=1.3.1
        - requests-mock
        - watchdog >=2.1.5
        - plotly >=5.3.1
        - testfixtures
        - matplotlib-base >=3.3.4
        - hypothesis >=6.17.4
        - python-graphviz >=0.17  # [py<313]
        # upstream pytest-benchmark==5.1.0, but only 4.0.0 is avaliable in main
        - pytest-benchmark >=4.0.0

about:
  home: https://streamlit.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The fastest way to build data apps in Python
  description: |
    Streamlit lets you turn data scripts into sharable web apps in minutes, not weeks.
    It's all Python, open-source, and free!
  doc_url: https://docs.streamlit.io/
  dev_url: https://github.com/streamlit/streamlit

extra:
  recipe-maintainers:
    - raybellwaves
    - randyzwitch
    - kmcgrady
  feedstock-name: streamlit
  skip-lints:
    # As we are only running the pytests in streamlit-tests we do not require python build tools
    - missing_python_build_tool
    - missing_wheel
