{% set name = "streamlit" %}
{% set version = "1.10.0" %}
{% set sha256 = "9479d623dd4bec1fc7bd27e85d5012672351210e640889022ee7b4631c4efb2c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/streamlit-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  # noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - streamlit = streamlit.cli:main
  skip: true  # [s390x or py<37]

requirements:
  host:
    - pip
    - python 
    - pipenv
    - setuptools
    - wheel
  run:
    - altair >=3.2.0
    - attrs >=16.0.0
    - blinker >=1.0.0
    - cachetools >=4.0
    - click >=7.0, <8.1
    - gitpython !=3.1.19
    - importlib-metadata >=1.4
    - numpy
    - packaging >=14.1
    - pandas >=0.21.0
    - pillow >=6.2.0
    - protobuf >=3.12,<4
    - pyarrow >=4.0
    - pydeck >=0.1.dev5
    - pympler >=0.9
    - python
    - python-dateutil
    - requests >=2.4
    - rich >=10.11.0
    - semver
    - toml
    - tornado >=5.0
    - typing_extensions >=3.10.0.0
    - tzlocal >=1.1
    - validators >=0.2
    - watchdog  # [not osx]

test:
  imports:
    - streamlit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://streamlit.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The fastest way to build data apps in Python
  description: |
    Streamlit lets you turn data scripts into sharable web apps in minutes, not weeks.
    It’s all Python, open-source, and free!
  doc_url: https://docs.streamlit.io/
  doc_source_url: https://github.com/streamlit/docs
  dev_url: https://github.com/streamlit/streamlit


extra:
  recipe-maintainers:
    - raybellwaves
    - randyzwitch
    - kmcgrady
